#!/usr/bin/env python3
import argparse
from venv import logger
from .repository_commands import rep_get_file
import logging


parser = argparse.ArgumentParser(description="Generar credenciales del fichero")


# rep_get_file <file_handle> <file> 
parser.add_argument("-v", '--verbose', help="Aumentar la verbosidad", action="store_true")
parser.add_argument('arg0', nargs='?', default=None)
parser.add_argument('arg1', nargs='?', default=None)
parser.add_argument('arg2', nargs='?', default=None)

args = parser.parse_args()

# Configuración del log según el nivel de verbosidad
if args.verbose:
    logger.setLevel(logging.DEBUG)
    logger.debug('Modo verbose activado. Log level establecido en DEBUG.')

# Llamar a la función para listar las organizaciones
rep_get_file(args.arg1, args.arg2)
