#!/usr/bin/env python3
import argparse
import os
import sys
from venv import logger
from .repository_commands import rep_subject_credentials
import logging

# rep_subject_credentials <password> <credentials_file>
parser = argparse.ArgumentParser(description="Generar credenciales de sujeto")

parser.add_argument("-p", '--password', nargs=1, required=True, help="Contraseña para proteger las credenciales")
parser.add_argument("-o", '--output', nargs=1, required=True, help="Archivo de salida para guardar la clave pública")
parser.add_argument("-v", '--verbose', help="Aumentar la verbosidad", action="store_true")
parser.add_argument('arg0', nargs='?', default=None)
parser.add_argument('arg1', nargs='?', default=None)
parser.add_argument('arg2', nargs='?', default=None)

args = parser.parse_args()

if args.verbose:
    logger.setLevel(logging.DEBUG)
    logger.debug('Modo verbose activado. Log level establecido en DEBUG.')

# Validar si el archivo de salida es válido
if os.path.exists(args.output[0]) and not os.access(args.output[0], os.W_OK):
    logger.error(f"No se puede escribir en el archivo especificado: {args.output[0]}")
    sys.exit(-1)

rep_subject_credentials(args.arg1, args.arg2)