#!/usr/bin/env python3
import argparse
from venv import logger
from .repository_commands import rep_add_subject
import logging

parser = argparse.ArgumentParser(description="Añade credenciales de sujeto")

# rep_add_subject <session_file> <username> <name> <email> <credentials_file>
parser.add_argument("-v", '--verbose', help="Aumentar la verbosidad", action="store_true")
parser.add_argument('arg0', nargs='?', default=None)
parser.add_argument('session_file', nargs='?', default=None)
parser.add_argument('username', nargs='?', default=None)
parser.add_argument('name', nargs='?', default=None)
parser.add_argument('email', nargs='?', default=None)
parser.add_argument('credentials_file', nargs='?', default=None)

args = parser.parse_args()

if args.verbose:
    logger.setLevel(logging.DEBUG)
    logger.debug('Modo verbose activado. Log level establecido en DEBUG.')


rep_add_subject(args.session_file, args.username, args.name, args.email, args.credentials_file)

