#!/usr/bin/env python3
import argparse
import os
import sys
from venv import logger
from .repository_commands import rep_create_org
import logging

# Parser de argumentos
parser = argparse.ArgumentParser(description="Crear una organización con sus credenciales.")
parser.add_argument("-v", '--verbose', help="Aumentar la verbosidad", action="store_true")
parser.add_argument('arg0', nargs='?', default=None)
parser.add_argument('arg1', nargs='?', default=None)
parser.add_argument('arg2', nargs='?', default=None)
parser.add_argument('arg3', nargs='?', default=None)
parser.add_argument('arg4', nargs='?', default=None)
parser.add_argument('arg5', nargs='?', default=None)

args = parser.parse_args()

# Configuración del log según el nivel de verbosidad
if args.verbose:
    logger.setLevel(logging.DEBUG)
    logger.debug('Modo verbose activado. Log level establecido en DEBUG.')

# Validación de la existencia y accesibilidad del archivo de clave pública
if not os.path.isfile(args.public_key):
    logger.error(f"El archivo de clave pública especificado no existe: {args.public_key}")
    sys.exit(-1)

# Llamar a la función para crear la organización
rep_create_org(args.arg1, args.arg2, args.arg3, args.arg4, args.arg5)