#!/usr/bin/env python3
import argparse
from venv import logger
from .repository_commands import rep_list_docs
import logging

parser = argparse.ArgumentParser(description="Generar una lista de documentos")

# rep_list_docs <session_file> <username> <date>
parser.add_argument("-v", '--verbose', help="Aumentar la verbosidad", action="store_true")
parser.add_argument('arg0', nargs='?', default=None)
parser.add_argument('arg1', nargs='?', default=None)
parser.add_argument('arg2', nargs='?', default=None)
parser.add_argument('arg3', nargs='?', default=None)

args = parser.parse_args()

if args.verbose:
    logger.setLevel(logging.DEBUG)
    logger.debug('Modo verbose activado. Log level establecido en DEBUG.')


rep_list_docs(args.arg1, args.arg2, args.arg3)